# Generated by Django 4.0.6 on 2022-08-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictusapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(null=True, to='pictusapp.hashtag'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
