# Generated by Django 4.0.6 on 2022-08-11 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictusapp', '0002_alter_post_hashtag_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
